config/routes.rb
School::Application.routes.draw do
  resources :clazzs

  get "classrooms/clazz_view", :to => "classrooms#clazz_view"
  get "classrooms/filter", :to => "classrooms#filter"
  resources :classrooms

  get "lessons/query", :to => "lessons#query"
  get "lessons/query_without_new", :to => "lessons#query_without_new"
  resources :lessons

  get "teachers/query", :to => "teachers#query"
  get "teachers/for_lesson/:id", :to => "teachers#for_lesson"
  resources :teachers

  get "students/for_classroom/:id", :to => "students#for_classroom"
  resources :students

  root :to =>  "classrooms#index"
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :registry
  validates_uniqueness_of :registry
  validates_presence_of :name, :registry

  belongs_to :classroom

  scope :with_no_classrooms, where("classroom_id IS NULL")
  scope :sorted, order(:name)

  def to_s
    name
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def for_classroom   
    @student = Student.find params[:id]
    render partial: "for_classroom", :locals => {:student => @student}
  end
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/views/students/_for_classroom.html.erb
<tr>
	<%= hidden_field_tag 'classroom[student_ids][]', student.id  %>
	<td>
		<%= student.name %>
	</td>
	<td>
		<button class="remove_student btn btn-danger" data-student-id="<%= student.id %>">Remover</button>
	</td>
</tr>

app/views/students/_form.html.erb
<%= simple_form_for @student, :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.input :name %>
    <%= f.input :registry %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  students_path, :class => 'btn' %>
    </div>
<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%= model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:registry) %></th>
      <th><%= model_class.human_attribute_name(:classroom) %></th>
      <th><%= t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.name, student_path(student) %></td>
        <td><%= student.registry %></td>
        <td><%= link_to student.classroom, classroom_path(student.classroom) if student.classroom %></td>
        <td>
          <%= link_to t("helpers.links.edit"),
                      edit_student_path(student), :class => 'btn btn-mini' %>
          <%= link_to t("helpers.links.destroy"),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:registry) %>:</strong></dt>
  <dd><%= @student.registry %></dd>
  <dt><strong><%= model_class.human_attribute_name(:classroom) %>:</strong></dt>
  <dd><%= @student.classroom %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>