config/routes.rb
School::Application.routes.draw do
  resources :clazzs

  get "classrooms/clazz_view", :to => "classrooms#clazz_view"
  get "classrooms/filter", :to => "classrooms#filter"
  resources :classrooms

  get "lessons/query", :to => "lessons#query"
  get "lessons/query_without_new", :to => "lessons#query_without_new"
  resources :lessons

  get "teachers/query", :to => "teachers#query"
  get "teachers/for_lesson/:id", :to => "teachers#for_lesson"
  resources :teachers

  get "students/for_classroom/:id", :to => "students#for_classroom"
  resources :students

  root :to =>  "classrooms#index"
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  #materia
  attr_accessible :name

  validates_uniqueness_of :name

  has_many :clazzs
  has_many :teachers, :through => :clazzs
  has_many :classrooms, :through => :clazzs

  scope :with_teachers, joins(:clazzs).joins(:teachers).uniq
  scope :with_teachers_and_no_classrooms,
        joins("LEFT JOIN clazzs ON clazzs.lesson_id = lessons.id").
        joins("INNER JOIN teachers ON clazzs.teacher_id = teachers.id").
        where("clazzs.id NOT IN (SELECT clazz_id FROM classrooms_clazzs)").uniq
  scope :sorted, order(:name)
  scope :query_without_new, lambda { |q| order(:name).where("name like ?", "%#{q}%")}

  def self.query query
    lessons = order(:name).where("name like ?", "%#{query}%")
    if lessons.empty?
      [{id: "<<<#{query.capitalize}>>>", name: "#{I18n.t('words.new')}: \"#{query.capitalize}\""}]
    else
      lessons.to_a
    end
  end

  def self.ids_from_names names
    names.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    names.split(',')
  end

  def to_s
    name
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  def query
    @lessons = Lesson.query(params[:q])
    respond_to do |format|
      format.json { render json: @lessons }
    end
  end

  def query_without_new
    @lessons = Lesson.query_without_new(params[:q])
    respond_to do |format|
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
end

app/views/lessons/_form.html.erb
<%= simple_form_for @lesson, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lessons_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lessons/index.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1>Matérias</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= link_to lesson.id, lesson_path(lesson) %></td>
        <td><%= lesson.name %></td>
        <td>
          <%= link_to t("helpers.links.edit"),
                      edit_lesson_path(lesson), :class => 'btn btn-mini' %>
          <%= link_to t("helpers.links.destroy"),
                      lesson_path(lesson),
                      :method => :delete,
                      :data => { :confirm => t("helpers.links.confirm") },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lesson_path,
            :class => 'btn btn-primary' %>

app/views/lessons/new.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lessons/show.html.erb
<%- model_class = Lesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @lesson.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lessons_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lesson_path(@lesson), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lesson_path(@lesson),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>