config/routes.rb
School::Application.routes.draw do
  resources :clazzs

  get "classrooms/clazz_view", :to => "classrooms#clazz_view"
  get "classrooms/filter", :to => "classrooms#filter"
  resources :classrooms

  get "lessons/query", :to => "lessons#query"
  get "lessons/query_without_new", :to => "lessons#query_without_new"
  resources :lessons

  get "teachers/query", :to => "teachers#query"
  get "teachers/for_lesson/:id", :to => "teachers#for_lesson"
  resources :teachers

  get "students/for_classroom/:id", :to => "students#for_classroom"
  resources :students

  root :to =>  "classrooms#index"
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  attr_accessible :name, :lessons_names
  attr_reader :lessons_names

  validates_presence_of :name

  has_many :clazzs
  has_many :lessons, :through => :clazzs
  has_many :classrooms, :through => :clazzs

  scope :sorted, order(:name)
  scope :query, lambda { |q| where("name like ?", "%#{q}%").sorted }

  def lessons_names=(names)
    self.lesson_ids = Lesson.ids_from_names(names)
  end

  def lessons_string
    lessons.map(&:name).join(", ")
  end

  def to_s
    name
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def query
    @teachers = Teacher.query(params[:q])
    respond_to do |format|
      format.json { render json: @teachers }
    end
  end

  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  def for_lesson
    @teachers = Lesson.find(params[:id]).teachers.sorted
    respond_to do |format|
      format.js
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
  def lessons_links_for_teacher teacher
    teacher.lessons.map{ |lesson| lesson_link(lesson)}.join(", ").html_safe
  end

  def lesson_link lesson
    link_to lesson, lesson_path(lesson)
  end
end

app/views/teachers/_alert_classrooms.html.erb
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Atenção!</strong>
  O Professor <%= @teacher %> ministra as aulas nas turmas <strong><%= @teacher.classrooms.map(&:name).join(",") %></strong>.

</div>

app/views/teachers/_form.html.erb
<%= simple_form_for @teacher, :html => {:class => 'form-horizontal'} do |f| %>

    <%= f.input :name %>
    <div class="control-group">
      <%= f.label :lessons, :class => 'control-label' %>
      <div class="controls" style="float: left; margin-left: 20px;">
        <%= f.text_field :lessons_names, :class => 'text_field', data: {load: @teacher.lessons} %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  teachers_path, :class => 'btn' %>
    </div>
<% end %>

app/views/teachers/edit.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%= model_class.model_name.human %></h1>
</div>

<% unless @teacher.classrooms.empty? %>
    <%= render "alert_classrooms" %>
<% end %>
<%= render :partial => 'form' %>

app/views/teachers/for_lesson.js.erb
$('#teachers').html('').append('<%= escape_javascript(options_from_collection_for_select(@teachers, "id", "name")) %>').trigger("liszt:updated");

app/views/teachers/index.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1>Professores</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:lessons) %></th>
      <th><%= t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= link_to teacher.id, teacher_path(teacher) %></td>
        <td><%= teacher.name %></td>
        <td><%= lessons_links_for_teacher(teacher) %></td>
        <td>
          <%= link_to t("helpers.links.edit"),
                      edit_teacher_path(teacher), :class => 'btn btn-mini' %>
          <%= link_to t("helpers.links.destroy"),
                      teacher_path(teacher),
                      :method => :delete,
                      :data => { :confirm => t("helpers.links.confirm") },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

app/views/teachers/new.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/show.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @teacher.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lessons) %>:</strong></dt>
  <dd><%= @teacher.lessons_string %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              teachers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teacher_path(@teacher), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teacher_path(@teacher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>