config/routes.rb
School::Application.routes.draw do
  resources :clazzs

  get "classrooms/clazz_view", :to => "classrooms#clazz_view"
  get "classrooms/filter", :to => "classrooms#filter"
  resources :classrooms

  get "lessons/query", :to => "lessons#query"
  get "lessons/query_without_new", :to => "lessons#query_without_new"
  resources :lessons

  get "teachers/query", :to => "teachers#query"
  get "teachers/for_lesson/:id", :to => "teachers#for_lesson"
  resources :teachers

  get "students/for_classroom/:id", :to => "students#for_classroom"
  resources :students

  root :to =>  "classrooms#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>School</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Gerenciador de turmas</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to t('activerecord.models.student').pluralize, students_path %></li>
          <li><%= link_to t('activerecord.models.teacher.other'), teachers_path %></li>
          <li><%= link_to t('activerecord.models.lesson.other'), lessons_path %></li>
          <li><%= link_to t('activerecord.models.classroom').pluralize, classrooms_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>
</body>
</html>